version: '3'

services:
 product-service:
  build: ./Products
  
  ports:
   - 5002:80


 client:
    image: appropriate/curl:latest
    command: "curl http://product-service:80"
    depends_on:
      - product-service